### ISSUE TITLE
请求作者帮忙解答

### ISSUE THREAD

**Issue by SYYYanyangyu** [kana-cr/exam-management#13]
你好 我拷贝你的代码发现很有学习价值 但在运行的过程中碰到一些问题  请问能回复一下吗 谢谢 这是我的联系方式1245938403

**Comment by kana-cr** [comment]
可以的，这个代码当时写的时候有很多不完善的地方，可以先在这里评论留下问题。如果是小问题，我可以直接讨论或者抽空改了更新仓库的代码。

**Comment by kana-cr** [comment]
主要是授权服务、阿里云oss存储服务、qq邮件smtp服务。一和三可以免费申请，二的话需要付费购买oss产品，当然自己想简单实现可以搭建一个简单的minio。如果想改造可以用spring的condition，如果想要直接使用可以考虑屏蔽相关类

**Comment by SYYYanyangyu** [comment]
首先非常感谢学长能抽空时间回我 谢谢！
我看到相关信息是你们大三的时候做的  我现在也是一名大三学生 
早上拷贝的时候 还能正常运行 但是在报名模块的时候个人信息userInfo 加载不出来 还有一个问题是端口问题 请问是前后端公用的是同一个端口吗 我修改了好多次都没成功 我也有阿里云的服务器 现阶段还没想过部署 能在本地跑起来就好了 我们最近在学习Java 所以希望学长能指点一下 谢谢 。
还有就是碰到的问题和这个卖源码的相似 我刚开始还以为这个是作者 抱歉 https://www.bilibili.com/video/BV1ai4y1171S?spm_id_from=333.337.search-card.all.click 这个是详细的问题秒速。
谢谢学长抽空回复 谢谢

**Comment by SYYYanyangyu** [comment]
首先非常感谢学长能抽空时间回我 谢谢！
我看到相关信息是你们大三的时候做的  我现在也是一名大三学生 
早上拷贝的时候 还能正常运行 但是在报名模块的时候个人信息userInfo 加载不出来 还有一个问题是端口问题 请问是前后端公用的是同一个端口吗 我修改了好多次都没成功 我也有阿里云的服务器 现阶段还没想过部署 能在本地跑起来就好了 我们最近在学习Java 所以希望学长能指点一下 谢谢 。
还有就是碰到的问题和这个卖源码的相似 我刚开始还以为这个是作者 抱歉 https://www.bilibili.com/video/BV1ai4y1171S?spm_id_from=333.337.search-card.all.click 这个是详细的问题秒速。
谢谢学长抽空回复 谢谢

**Comment by kana-cr** [comment]
不能一个端口～ 能否给我指明一下是哪个接口呢，我一下回忆不起来了～ 有细节问题可以加我QQ 862336406

**Comment by SYYYanyangyu** [comment]
我昨天看了一会就是vue的请求的端口为啥用的是启动端口的 总共有三处地方我都试了 但还是解决不了这个问题 
还有就是那天晚上收到消息 太晚了怕打扰学长休息 白天加的 麻烦学长同意下 在不打扰学长的情况下 抽空解答一下 谢谢

**Comment by kana-cr** [comment]
可以加我QQ 862336406
