### ISSUE TITLE
这代码写的太差了吧？

### ISSUE THREAD

**Issue by DreamsCat** [kana-cr/exam-management#14]
BUG巨多，表设计不合理，这么差的代码就别往上放了

**Comment by kana-cr** [comment]
见谅，是刚学的时候写的，bug和不合理的地方是不少，但是如果不喜欢能否不要张口就是否定呢。毕竟只是个demo，何必如此认真，至于表结构设计的不合理可以认同，但是能否指出不合理之处呢。觉得烂就喜欢点踩，然后又不指出具体system design上不合理的点，是否不妥呢？没必要这样，毕竟也有很多初学者需要这样一份demo，至于bug大多都是因为中间件和配置问题，个人当时没有做condition。
