### ISSUE TITLE
提示找不到符号

### ISSUE THREAD

**Issue by zhangyebo1991** [kana-cr/exam-management#4]
Error:(85, 22) java: 找不到符号
  符号:   方法 deleteFileUrl(java.lang.String)
  位置: 类型为us.sep.util.aliyun.AliyunOssUtil的变量 aliyunOssUtil

请问下提示找不到符号，好像是这个方法还没写么？看到好几个方法都没有

**Comment by kana-cr** [comment]
谢谢提醒，之前因为仓库的迁移导致这个仓库不是线上版本，在合并的时候出了一点问题没有关注到，现在已经修复。
