### ISSUE TITLE
登录的拼图问题

### ISSUE THREAD

**Issue by arraycto** [kana-cr/exam-management#7]
如上一个issues，的确代码风格思路很清晰。
请问您的这个登录拼图的思路是：
1.从oss获取随机图片（后端api获取）
2.前端进行随机生成坐标（该步骤与后端无关？）
3.验证（前端行为）
不知道理解对否？如果不对，请指点一下思路。

**Comment by kana-cr** [comment]
接口获取image表中的OSS存储的图片地址，然后前端再生成渲染以及验证。因为前端不是本人实现的，是其他组员的成品 @dgxgefg1 ，可以去他的fork库和他讨论讨论。

**Comment by arraycto** [comment]
感谢兄弟。你可以研究一下minio （免费，学生实用），类似阿里的oss。minio或者fastdfs。供参考~

**Comment by kana-cr** [comment]
好的，谢谢(*￣︶￣)
