### ISSUE TITLE
最新版本编译不过请教下

### ISSUE THREAD

**Issue by zhangyebo1991** [kana-cr/exam-management#8]
下载了最新版本，编译还会有问题，这是为什么，请教一下
D:\games\exam-management-main\spring-module\exam-web\src\main\java\us\sep\user\controller\UserController.java:273:121
java: 找不到符号
  符号:   方法 ifManagerOrAdmin(java.lang.String)
  位置: 类型为us.sep.biz.user.service.UserService的变量 userService

**Comment by kana-cr** [comment]
谢提醒，已修复。
